# Generated by Django 4.2.16 on 2026-02-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeedShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('crop_available', models.CharField(max_length=100)),
                ('price_range', models.CharField(max_length=50)),
                ('contact_info', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
