# Generated by Django 4.2.16 on 2026-02-12 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedshop',
            name='district',
            field=models.CharField(default='Kerala', max_length=100),
        ),
        migrations.AddField(
            model_name='seedshop',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seedshop',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='UserCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('status', models.CharField(default='Growing', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
